### ISSUE TITLE
`Waifu.pics` API URL has been changed

### ISSUE THREAD

**Issue by thanhgaming5550** [elliottophellia/kyoko#1]
https://waifu.pics/docs

![image](https://user-images.githubusercontent.com/62001770/210033427-2ae67756-70ef-49f2-8914-a1df732628db.png)

**Comment by elliottophellia** [comment]
em.. i think you read it mistake, it's switching from waifu.pics/api to api.waifu.pics, and Kyoko already using api.waifu.pics.
