### ISSUE TITLE
add more description to the random anime aka the waifu api

### ISSUE THREAD

**Issue by gamersindo1223** [elliottophellia/kyoko#2]
hello is it possible to add some description  to the random waifu category?
like the name of the character, the description or where the character belongs to
thanks

**Comment by elliottophellia** [comment]
> hello is it possible to add some description to the random waifu category? like the name of the character, the description or where the character belongs to thanks

Well it's not impossible but, you see Kyoko it's just wrapper for WaifuPics and their API don't have that kind of description, to make it have description it's kinda problem cus you need to have SauceNao Premium API key to recognize the ART and put source on it.
